Copy DEFRA-backend and Planting-Tools image release, publish SHA images and merge

diff --git a/.github/workflows/test-publish.yml b/.github/workflows/test-publish.yml
--- a/.github/workflows/test-publish.yml
+++ b/.github/workflows/test-publish.yml
@@ -37,9 +37,7 @@ jobs:
           concurrent_skipping: same_content_newer
 
   build_and_test:
-  
     needs: skip_check
-
     strategy:
       fail-fast: false # stop GH from cancelling all matrix builds if one fails
       #max-parallel: 1
@@ -50,9 +48,6 @@ jobs:
             platform: amd64
           - os: ubuntu-24.04-arm
             platform: arm64
-          
-        #  - platform: amd64
-        #  - platform: arm64
     
     runs-on: ${{ matrix.os }}
     
@@ -66,6 +61,7 @@ jobs:
     outputs:
       DGPSI_FOLDER_NAME: ${{ steps.set_dgpsi_folder_name.outputs.DGPSI_FOLDER_NAME }}
       DOCKER_IMAGE_CACHE_SCOPE: ${{ steps.docker_image_cache_scope.outputs.DOCKER_IMAGE_CACHE_SCOPE }}
+      stop: ${{ steps.publish_or_not.outputs.stop }}
 
     steps:
       
@@ -104,7 +100,7 @@ jobs:
           file: Dockerfile
           #platforms: ${{ matrix.platform }}
           load: true
-          tags: test_rstudio
+          tags: image-${{ matrix.platform }}
           build-args: DGPSI_FOLDER_NAME=${{ env.DGPSI_FOLDER_NAME }}
           cache-from: type=gha,scope=${{ env.DOCKER_IMAGE_CACHE_SCOPE }}-${{ matrix.platform }}
           cache-to: type=gha,mode=max,scope=${{ env.DOCKER_IMAGE_CACHE_SCOPE }}-${{ matrix.platform }}
@@ -117,7 +113,7 @@ jobs:
                   --detach \
                   --name "$container_name" \
                   --publish 8787:8787 \
-                  test_rstudio)
+                  image-${{ matrix.platform }})
 
           # First launch
           echo "============== Waiting 30 seconds for container to boot... ==============" 
@@ -132,12 +128,19 @@ jobs:
           interval=10   # check every 10 seconds
           elapsed=0
 
-          echo "============== Container started: $cid =============="
-          echo "============== Waiting up to $((max_wait/60)) minutes for container to be ready... =============="
+          echo "============== Container started: $cid. Waiting up to $((max_wait/60)) minutes for container to be ready... =============="
 
+          logs_since=$(date -u +"%Y-%m-%dT%H:%M:%S.%NZ")
           while [ $elapsed -lt $max_wait ]; do
 
             echo
+
+            echo  "============== Docker stats =============="
+            docker stats --no-stream "$cid"
+            
+            echo  "============== System disk stats =============="
+            df -h
+            free -h
 
             # Check if container is still running
             status=$(docker inspect --format '{{.State.Status}}' "$cid" 2>/dev/null)
@@ -145,8 +148,7 @@ jobs:
             [ -z "$status" ] && status="not-found"
             
             if [ "$status" != "running" ]; then
-              echo "============== Container stopped with status: $status =============="
-              echo "============== Container stopped running, printing logs =============="
+              echo "============== Container stopped with status: $status. Printing logs =============="
               docker logs "$cid"
 
               exit_code=$(docker inspect --format '{{.State.ExitCode}}' "$cid" 2>/dev/null)
@@ -157,134 +159,147 @@ jobs:
             
             echo "============== Checking health =============="
             health=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 "http://localhost:8787/unsupported_browser.htm" || true)
+            # Define times (since and until) to avoid overlap with next loop's logs
+            logs_until=$(docker logs --tail 1 --timestamps "$cid" 2>&1 | cut -d ' ' -f 1)
+            
             if [ $health -eq 200 ]; then
               echo "============== Valid healthcheck, printing logs then terminating =============="
-              docker logs --since "${interval}s" "$cid"
+              docker logs --since "$logs_since" --until "$logs_until" "$cid"
               exit 0
             elif [ -z "$health" ]; then
               echo "============== Curl error from healthcheck timeout, container is likely busy. Logs since ${interval} seconds ago: =============="
-              docker logs --since "${interval}s" "$cid"
+              docker logs --since "$logs_since" --until "$logs_until" "$cid"
             else
               echo "============== Unexpected healthcheck, printing it =============="
-              echo "============== $health =============="
+              echo "health=$health"
             fi
 
-            echo "============== [${elapsed}s] Container status is running (status: $status), waiting... =============="
-            sleep "$((interval))"
+            echo "============== [${elapsed}s] Container status is running (status: $status), waiting ${interval} seconds... =============="            sleep "$((interval))"
+            sleep "$interval"
             elapsed=$((elapsed + interval))
           done
 
           echo
-          echo "============== "===== $((max_wait/60)) minutes elapsed, container still running ===== =============="
-          echo "============== Container still running, printing all logs =============="
+          echo "============== $((max_wait/60)) minutes elapsed, container still running, printing all logs =============="
           docker logs "$cid"
 
           echo
           echo "============== Healthcheck =============="
-          health=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 "http://localhost:8787/unsupported_browser.htm" || true)
+          health=$(curl -sS --max-time 10 "localhost:40000/health" || true)
+          echo
           echo "============== health =============="
-          echo "============== $health =============="
+          echo "$health"
           if [ $health -eq 200 ]; then
+            echo
             echo "============== Container unhealthy or error, logs: =============="
             docker logs --since 5s "$cid"
+            echo
             echo "============== Exiting... =============="
             exit 101
           fi
+          echo
           echo "============== Container ready, proceeding to next task =============="
           docker rm --fv "$cid"
 
-  publish_temp_images:
-    needs: build_and_test
-  
-    strategy:
-      fail-fast: false # stop GH from cancelling all matrix builds if one fails
-      matrix:
-        # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
-        include:
-          - os: ubuntu-latest
-            platform: amd64
-          - os: ubuntu-24.04-arm
-            platform: arm64
-    
-    runs-on: ${{ matrix.os }}
+      - name: Debug env variables to test if next part runs
+        run: |
+          echo "github.event_name = ${{ github.event_name }}"
+          echo "github.ref_name = ${{ github.ref_name }}"
+          if [[ ${{ github.event_name }} = 'pull_request' ]]; then
+            echo "github.event.pull_request.merged = ${{ github.event.pull_request.merged }}"
+            echo "github.event.pull_request.base.ref = ${{ github.event.pull_request.base.ref }}"
+          elif [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
+            echo "inputs.publish=${{ inputs.publish }}"
+          fi
+          
+          echo
+          echo "Condition 1 = ${{ github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'dev') }}"
+          echo "Condition 2 = ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true && (github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'dev') }}"
+          echo "Condition 3 = ${{ github.event_name == 'workflow_dispatch' && inputs.publish == true }}"
 
-    # Only actually publish on push and merged PR to main/dev, or forcefully on workflow_dispatch
-    if: |
-      (github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'dev')) ||
-      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && (github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'dev')) ||
-      (github.event_name == 'workflow_dispatch' && inputs.publish == true)
-    
-    permissions:
-      contents: read
-      packages: write
+          echo "Print environment github variables"
+          env | grep -i github
 
-    outputs:
-      SHORT_SHA_TAG_SUFFIX: ${{ steps.tag_variables.outputs.SHORT_SHA_TAG_SUFFIX }}
-      REPO_OWNER: ${{ steps.tag_variables.outputs.REPO_OWNER }}
-      PACKAGE: ${{ steps.tag_variables.outputs.PACKAGE }}
+          echo
+          echo Condition 1 = $([[ "$GITHUB_EVENT_NAME" == "push" && ( "$GITHUB_REF_NAME" == "main" || "$GITHUB_REF_NAME" == "dev" ) ]] && echo true || echo false)
+          echo Condition 2 = $([[ "$GITHUB_EVENT_NAME" == "pull_request" && "$GITHUB_EVENT_PULL_REQUEST_MERGED" == "true" && ( "$GITHUB_EVENT_PULL_REQUEST_BASE_REF" == "main" || "$GITHUB_EVENT_PULL_REQUEST_BASE_REF" == "dev" ) ]] && echo true || echo false)
+          echo Condition 3 = $([[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" && "$INPUT_PUBLISH" == "true" ]] && echo true || echo false)
+          echo '1 || 2 = '"$([[ "$GITHUB_EVENT_NAME" == "push" && ( "$GITHUB_REF_NAME" == "main" || "$GITHUB_REF_NAME" == "dev" ) ]] || \
+            [[ "$GITHUB_EVENT_NAME" == "pull_request" && "$GITHUB_EVENT_PULL_REQUEST_MERGED" == "true" && ( "$GITHUB_EVENT_PULL_REQUEST_BASE_REF" == "main" || "$GITHUB_EVENT_PULL_REQUEST_BASE_REF" == "dev" ) ]] && \
+            echo true || echo false)"
+          echo '1 || 3 = '"$([[ "$GITHUB_EVENT_NAME" == "push" && ( "$GITHUB_REF_NAME" == "main" || "$GITHUB_REF_NAME" == "dev" ) ]] || \
+            [[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" && "$INPUT_PUBLISH" == "true" ]] && \
+            echo true || echo false)"
+          echo '2 || 3 = '"$([[ "$GITHUB_EVENT_NAME" == "pull_request" && "$GITHUB_EVENT_PULL_REQUEST_MERGED" == "true" && ( "$GITHUB_EVENT_PULL_REQUEST_BASE_REF" == "main" || "$GITHUB_EVENT_PULL_REQUEST_BASE_REF" == "dev" ) ]] || \
+            [[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" && "$INPUT_PUBLISH" == "true" ]] && \
+            echo true || echo false)"
+          echo '1 || 2 || 3 = '"$([[ "$GITHUB_EVENT_NAME" == "push" && ( "$GITHUB_REF_NAME" == "main" || "$GITHUB_REF_NAME" == "dev" ) ]] || \
+            [[ "$GITHUB_EVENT_NAME" == "pull_request" && "$GITHUB_EVENT_PULL_REQUEST_MERGED" == "true" && ( "$GITHUB_EVENT_PULL_REQUEST_BASE_REF" == "main" || "$GITHUB_EVENT_PULL_REQUEST_BASE_REF" == "dev" ) ]] || \
+            [[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" && "$INPUT_PUBLISH" == "true" ]] && \
+            echo true || echo false)"
 
-    steps:
-      
-      - name: Checkout repository
-        uses: actions/checkout@v7
-
-      # Set up BuildKit Docker container builder to be able to build
-      # multi-platform images and export cache
-      # https://github.com/docker/setup-buildx-action
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v4
-      
-      ## https://github.com/docker/setup-qemu-action
-      #- name: Set up QEMU
-      #  uses: docker/setup-qemu-action@v4
+      - name: Publish?
+        id: publish_or_not
+        run: |
+          #(github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'dev')) ||
+          #(github.event_name == 'pull_request' && github.event.pull_request.merged == true && (github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'dev')) ||
+          #(github.event_name == 'workflow_dispatch' && inputs.publish == true)
+          if { 
+            [[ "$GITHUB_EVENT_NAME" == "push" && ( "$GITHUB_REF_NAME" == "main" || "$GITHUB_REF_NAME" == "dev" ) ]] ||
+            [[ "$GITHUB_EVENT_NAME" == "pull_request" && "$GITHUB_EVENT_PULL_REQUEST_MERGED" == "true" && ( "$GITHUB_EVENT_PULL_REQUEST_BASE_REF" == "main" || "$GITHUB_EVENT_PULL_REQUEST_BASE_REF" == "dev" ) ]] ||
+            [[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" && "$INPUT_PUBLISH" == "true" ]]
+          }; then
+            stop="false"
+          else
+            stop="true"
+          fi
+          echo "stop=$stop" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
 
       # Login against a Docker registry except on PR
       # https://github.com/docker/login-action
       - name: Log into registry ${{ env.REGISTRY }}
-        uses: docker/login-action@v4.6.0
+        if: env.stop == 'false'
+        uses: docker/login-action@v4
         with:
           registry: ${{ env.REGISTRY }}
           username: ${{ github.actor }}
           password: ${{ github.token }}
 
-      - name: Create tag variables
-        id: tag_variables
-        run: |
-          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
-          echo "REPO_OWNER=$REPO_OWNER" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
 
-          PACKAGE=$(echo "${{ github.repository }}" | cut -d "/" -f 2 | tr "[:upper:]" "[:lower:]")
-          echo "PACKAGE=$PACKAGE" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
-
-          github_sha_hash="${{ github.sha }}"
-          SHORT_SHA_TAG_SUFFIX="${github_sha_hash:0:7}"
-          echo "SHORT_SHA_TAG_SUFFIX=$SHORT_SHA_TAG_SUFFIX" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
-
-      # Build and push Docker image with Buildx (don't push on PR)
-      # https://github.com/docker/build-push-action
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v7
+      # https://github.com/docker/metadata-action
+      - name: Extract metadata (tags, labels) for Docker
+        if: env.stop == 'false'
+        id: meta
+        uses: docker/metadata-action@v6
         with:
-          context: .
-          file: Dockerfile
-          #platforms: linux/amd64,linux/arm64
-          build-args: DGPSI_FOLDER_NAME=${{ needs.build_and_test.outputs.DGPSI_FOLDER_NAME }}
-          pull: true
-          push: true
-          tags: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.PACKAGE }}:temp-${{ matrix.platform }}-${{ env.SHORT_SHA_TAG_SUFFIX }}
-          #tags: ${{ steps.meta.outputs.tags }}
-          #labels: ${{ steps.meta.outputs.labels }}
-          cache-from: type=gha,scope=${{ needs.build_and_test.outputs.DOCKER_IMAGE_CACHE_SCOPE }}-${{ matrix.platform }}
-          cache-to: type=gha,mode=max,scope=${{ needs.build_and_test.outputs.DOCKER_IMAGE_CACHE_SCOPE }}-${{ matrix.platform }}
+          images: ${{ env.REGISTRY }}/${{ github.repository }}
+          tags: |
+            type=sha
+          labels: |
+            org.opencontainers.image.created={{commit_date 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'}}
+      
+      - name: Push the already-built image
+        if: env.stop == 'false'
+        run: |
+          echo "docker images"
+          docker images
+          
+          TAG="${{ fromJSON(steps.meta.outputs.json).tags[0] }}-${{ matrix.platform }}"
+          echo "Tagging image-${{ matrix.platform }} to $TAG"
+          docker tag image-${{ matrix.platform }} "$TAG"
+          
+          echo "Pushing the image to $TAG"
+          docker push "$TAG"
+
 
   merge_images_and_publish:
-    needs: publish_temp_images
-
+    needs: build_and_test
     runs-on: ubuntu-latest
-
     permissions:
       contents: read
       packages: write
+    
+    if: needs.build_and_test.outputs.stop == 'false'
     
     steps:
       
@@ -331,18 +346,32 @@ jobs:
           labels: |
             org.opencontainers.image.created={{commit_date 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'}}
 
+      - name: Create tag
+        run: |
+          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
+          echo "REPO_OWNER=$REPO_OWNER" | tee -a $GITHUB_ENV
+          
+          PACKAGE=$(echo "${{ github.repository }}" | cut -d "/" -f 2 | tr "[:upper:]" "[:lower:]")
+          echo "PACKAGE=$PACKAGE" | tee -a $GITHUB_ENV
+          
+          BASE_TAG="${{ env.REGISTRY }}/${REPO_OWNER}/${PACKAGE}"
+          echo "BASE_TAG=$BASE_TAG" | tee -a $GITHUB_ENV
+
       - name: Create final multi-arch image
         run: |
           echo "============== Tags with -t =============="
           echo "$(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON")"
+          
+          # Extract the SHA tag
+          SHA_TAG=$(jq -r '.tags | map(select(contains(":sha-"))) | .[0]' <<< "$DOCKER_METADATA_OUTPUT_JSON")
 
           # Run imagetools create with the dynamic array of tags and both arch images
           docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
-            "${{ env.REGISTRY }}/${{ needs.publish_temp_images.outputs.REPO_OWNER }}/${{ needs.publish_temp_images.outputs.PACKAGE }}:temp-amd64-${{ needs.publish_temp_images.outputs.SHORT_SHA_TAG_SUFFIX }}" \
-            "${{ env.REGISTRY }}/${{ needs.publish_temp_images.outputs.REPO_OWNER }}/${{ needs.publish_temp_images.outputs.PACKAGE }}:temp-arm64-${{ needs.publish_temp_images.outputs.SHORT_SHA_TAG_SUFFIX }}"
+            "${SHA_TAG}-amd64" \
+            "${SHA_TAG}-arm64"
     
-      - name: Delete temporary GHCR tags
-        uses: dataaxiom/ghcr-cleanup-action@v1
-        with:
-          packages: ${{ needs.publish_temp_images.outputs.PACKAGE }}
-          delete-tags: "temp-*-${{ needs.publish_temp_images.outputs.SHORT_SHA_TAG_SUFFIX }}"
+      # - name: Delete temporary GHCR tags
+      #   uses: dataaxiom/ghcr-cleanup-action@v1
+      #   with:
+      #     packages: ${{ needs.publish_temp_images.outputs.PACKAGE }}
+      #     delete-tags: "temp-*-${{ needs.publish_temp_images.outputs.SHORT_SHA_TAG_SUFFIX }}"
